MovieShopMVC/Models/ErrorViewModel.cs
namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShopMVC/Controllers/AccountController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MovieShopMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService _accountService;

        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginModel model)
        {
            var userSuccess = await _accountService.ValidateUser(model);
            if (userSuccess == null)
            {
                // pasword matches
                // redirect to home page
                return View();
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email, userSuccess.Email),
                new Claim(ClaimTypes.NameIdentifier, userSuccess.Id.ToString()),
                new Claim(ClaimTypes.Surname, userSuccess.LastName),
                new Claim(ClaimTypes.GivenName, userSuccess.FirstName)
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
            return LocalRedirect("~/");
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterModel model)
        {
            var userId = await _accountService.RegisterUser(model);

            if (userId > 0)
            {
                // redirect to login page
                return RedirectToAction("Login");
            }

            return View();

        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

MovieShopMVC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;

        public CastController(ICastService castService)
        {
            _castService = castService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var castDetails = await _castService.GetCastDetails(id);
            return View(castDetails);
        }
    }
}

MovieShopMVC/Controllers/HomeController.cs
using ApplicationCore.Contracts.Services;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Models;
using System.Diagnostics;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMovieService _movieService;
        public HomeController(ILogger<HomeController> logger, IMovieService movieService)
        {
            _logger = logger;
            _movieService = movieService;
        }

        // Action methods
        public async Task<IActionResult> Index()
        {
            var movies = await _movieService.GetTop30GrossingMovies();
            return View(movies);
        }

        // http://movieshop.com/home/privacy
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Details(int id)
        {
             var movieDetails = await _movieService.GetMovieDetails(id);
             return View(movieDetails);
        }

        public async Task<IActionResult> GenreMovies(int Id, int pageSize = 30, int page = 1)
        {
            var pagedMovies = await _movieService.GetMoviesByPagination(Id, pageSize, page);
            return View(pagedMovies);
        }
    }
}

MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Infra;

namespace MovieShopMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ICurrentUser _currentUser;

        public UserController(ICurrentUser currentUser)
        {
            _currentUser = currentUser;
        }
        [HttpGet]
        public async Task<IActionResult> Purchases()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> EditProfile()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EditProfile(UserRegisterModel model)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BuyMovie()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Favorites()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> FavoriteMovie()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

MovieShopMVC/Views/Cast/Details.cshtml
@model ApplicationCore.Models.CastDetailsModel
<!DOCTYPE html>

<h3 align="center">@Model.Name</h3>
<center><img align = "center" height = "350px" width = "255px" src = "@Model.ProfilePath" /></center>
<br />
<h5 align = "center">Movies</h5>
 <ul class="list-group list-group-flush">
                 @foreach(var movie in @Model.Movies)
                {
                  <a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id"><li class="list-group-item">@movie.Title</li></a>
                }
 </ul>

MovieShopMVC/Views/Home/Index.cshtml
@model List<ApplicationCore.Models.MovieCardModel>

@{
    ViewData["Title"] = "Home Page";
}

@*Display top 30 highest grossing movies, as movie cards *@

<div class="rounded">
    <div class="container-fluid">
        <div class="row">

            @foreach (var movieCard in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    <partial name="_MovieCard" model="movieCard" />
                </div>
            }

        </div>
    </div>
</div>

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsModel

<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width initial-scale=1.0"/>
    <title>@Model.Title Details</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" />
    <style>
        .row-1 {
          background-image: url('@Model.BackdropUrl');
          background-color: rgba(255, 255, 255, 0.6);
          background-blend-mode: overlay;
        }
    </style>
</head>

<div class="container">
    <div class="row row-1" height = "300px">
        <div class="col">
            <img src="@Model.PosterUrl" align = "middle" height="300px" width="200px"/>
        </div>
        <div class="col-5" align="left">
            <h3 style="color: black">@Model.Title</h3>
            <p style="color: black; font-size:10px;">@Model.Tagline
            @foreach (var genre in @Model.Genres)
               { <a asp-controller="Movies" asp-action="GenreMovies" asp-route-id="@genre.Id"><span class="badge alert-success">@genre.Name</span></a>}
               </p>
            <h6><span class="badge alert-success">Rating</span></h6>
            <p style="color: black; font-size:12px;">@Model.RunTime m | @Model.ReleaseDate</p>
            <p style="color: black; font-size:12px;">@Model.Overview</p>
        </div>
        <div class="col" align = "right">
            <div class="d-grid gap-2">
                <br /><br />
            <button type="button" class="btn btn-dark" width="500px" data-bs-toggle="modal" data-bs-target="#reviewModal"><b>REVIEW</b></button>
                    
                    <div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="reviewModalLabel">Review</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                                 <div class="dropdown" align ="left">
                                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                        Rating
                                      </button>
                                      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                        <li><a class="dropdown-item" href="#">1</a></li>
                                        <li><a class="dropdown-item" href="#">2</a></li>
                                        <li><a class="dropdown-item" href="#">3</a></li>
                                        <li><a class="dropdown-item" href="#">4</a></li>
                                        <li><a class="dropdown-item" href="#">5</a></li>
                                        <li><a class="dropdown-item" href="#">6</a></li>
                                        <li><a class="dropdown-item" href="#">7</a></li>
                                        <li><a class="dropdown-item" href="#">8</a></li>
                                        <li><a class="dropdown-item" href="#">9</a></li>
                                        <li><a class="dropdown-item" href="#">10</a></li>
                                      </ul>
                                </div>
                                <br />
                                <form align = "left">
                                      <label for="fname">Write Review:</label><br>
                                      <input type="text" id="review" name="review"><br>
                                </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Submit</button>
                          </div>
                        </div>
                      </div>
                    </div>

            <button type="button" class="btn btn-dark" width="500px" data-bs-toggle="modal" data-bs-target="#buyModal"><b>BUY $@Model.Price</b></button>
                    <div class="modal fade" id="buyModal" tabindex="-1" aria-labelledby="buyModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="buyModalLabel">Purchase</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                  </div>
                                  <div class="modal-body">
                                        <h6 align = "left">Price of the movie: $@Model.Price</h6>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a asp-controller="User" asp-action="BuyMovie" class="btn btn-primary">Purchase</a>
                                  </div>
                                </div>
                              </div>
                     </div>
            </div>
        </div>
    </div>
    <br />

  <div class="row">
        <div class="col">
            <h6 align="left">MOVIE FACTS</h6>
            <hr />
            <ul class="list-group list-group-flush">
                  <li class="list-group-item">Release Date&nbsp; <span class="badge alert-success" align = "right"> @Model.ReleaseDate</span></li>
                  <li class="list-group-item">Run Time&nbsp; <span class="badge alert-success"> @Model.RunTime m</span></li>
                  <li class="list-group-item">Box Office&nbsp; <span class="badge alert-success"> $@Model.Budget</span></li>
            </ul>
            <br />
            <h6 align="left">TRAILERS</h6>
            <hr />
            <ul class="list-group list-group-flush">
                 @foreach(var trailer in @Model.Trailers)
                {
                  <li class="list-group-item"><a style="color: black" href="@trailer.TrailerUrl">@trailer.Name</a></li>
                }
            </ul>
        </div>
        <div class="col-5" align="center">
            <h6 align = "left">CAST</h6>
            <hr />
            <div class = "container">
                @foreach(var cast in @Model.Casts)
                {
                   <div class = "row">
                       <div class = "col" align = "center"><img style="border-radius: 50%; height: 50px; width: 35px" src="@cast.ProfilePath" alt="CastPic"></div>
                        <div class = "col" align = "left"><p style="font-size: 12px"><a style="color: black" asp-controller="Cast" asp-action="Details" asp-route-id="@cast.Id">@cast.Name</a></p></div>
                            <div class = "col" align = "left"><p style="font-size: 12px">@cast.Character</p></div>
                   </div>
                   <hr />
                }
            </div>
            
        </div>
        <div class="col">

        </div>
    </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reviewModal">Review</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    Rating
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="#">1</a></li>
                    <li><a class="dropdown-item" href="#">2</a></li>
                    <li><a class="dropdown-item" href="#">3</a></li>
                    <li><a class="dropdown-item" href="#">4</a></li>
                    <li><a class="dropdown-item" href="#">5</a></li>
                    <li><a class="dropdown-item" href="#">6</a></li>
                    <li><a class="dropdown-item" href="#">7</a></li>
                    <li><a class="dropdown-item" href="#">8</a></li>
                    <li><a class="dropdown-item" href="#">9</a></li>
                    <li><a class="dropdown-item" href="#">10</a></li>
                  </ul>
            </div>
            <form>
                  <label for="fname">Write Review:</label><br>
                  <input type="text" id="review" name="review"><br>
            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>



</html>

MovieShopMVC/Views/Movies/GenreMovies.cshtml
@using ApplicationCore.Models;
@model PagedResultSet<MovieCardModel>;

@{
    ViewData["Title"] = "Genre";
}

@*Display top 30 highest grossing movies, as movie cards *@

<div class="rounded">
    <div class="container-fluid">
        <div class="row">

            @foreach (var movieCard in Model?.Data)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    <partial name="_MovieCard" model="movieCard" />
                </div>
            }

        </div>
    </div>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="GenreMovies" asp-route-page = "@(Model.PageIndex - 1)" class="btn btn-primary @prevDisabled" prevDisabled>Previous</a>
<a asp-action="GenreMovies" asp-route-page = "@(Model.PageIndex + 1)" class="btn btn-primary @nextDisabled" nextDisabled>Next</a>

MovieShopMVC/Views/Shared/_GenreDropdown.cshtml
@using ApplicationCore.Contracts.Services
@inject IGenreService genreService

    <ul class="nav">
           <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">
                   Genres
               </a>
               <div class="dropdown-menu">
            @foreach(var genre in await genreService.GetAllGenres())
            {
                     <a class="dropdown-item" asp-controller="Movies" asp-action="GenreMovies" asp-route-id="@genre.Id">@genre.Name</a>
                }
               </div>
           </li>
    </ul>

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_GenreDropdown" />
                    <partial name="_LoginInfoPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_LoginInfoPartial.cshtml
@using MovieShopMVC.Infra
@inject ICurrentUser currentUser


@if (currentUser.IsAuthenticated)
{
    <div class="text-end">
       <ul class="nav">
           <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">
                   @currentUser.FullName
               </a>
               <div class="dropdown-menu">
                   <a class="dropdown-item" asp-controller="User" asp-action="Purchases"> Purchases</a>
                   <a class="dropdown-item" asp-controller="User" asp-action="Favorites"> Favorites</a>
                   <a class="dropdown-item" asp-controller="User" asp-action="EditProfile"> Edit Profile</a>
                   <a class="dropdown-item" asp-controller="Account" asp-action="Logout"> Logout</a>
               </div>
           </li>
        </ul>
    </div>
}

else{
    <div class="text-end">
        <a class="btn btn-outline-dark me-2" asp-controller="Account" asp-action="Login">Login</a>
        <a class="btn btn-outline-dark" asp-controller="Account" asp-action="Register">Register</a>
    </div>
}

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardModel
<div class="card mb-4">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id"  >
        <img src="@Model.PosterUrl" class="img-fluid" />
    </a>
</div>

MovieShopMVC/Views/User/BuyMovie.cshtml
@model ApplicationCore.Models.MovieDetailsModel

<h5>Receipt</h5>
<hr>
<center>
<img height="300px" width="250px" src = "@Model.PosterUrl" />
<h6>Movie:$nbsp @Model.Title</h6>
<h6>Total Price:$nbsp @Model.Price</h6>
</center>

MovieShopMVC/Views/User/EditProfile.cshtml
@model ApplicationCore.Models.UserRegisterModel

@{
    ViewData["Title"] = "Edit Profile";
}
<h4>Register</h4>
<hr />
<div class="row">
    <div class="col-md-4">  
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Date Of Birth</label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Confirm Changes</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieShopMVC/Views/User/Favorites.cshtml
<h4>Favorite Movies</h4>

MovieShopMVC/Views/User/Purchases.cshtml
@model ApplicationCore.Models.PurchaseModel

@{
    ViewData["Title"] = "Purchases";
}
<h4>Purchases</h4>
<hr />
<ul class="list-group list-group-flush">
                         <h6>MovieId: @Model.MovieId</h6>
                         <h6>UserId: @Model.UserId</h6>
                         <h6>Date: @Model.PurchaseDateTime</h6>
                         <h6>Price: @Model.TotalPrice</h6>               
 </ul>